apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    name: springboot
    app: spring-app
spec:
  selector:
    name: springboot
    app: spring-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30010
